apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: sheshta-app

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-all
  namespace: sheshta-app
subjects:
- kind: ServiceAccount
  name: webapp-sa
roleRef:
  kind: Role
  name: secret-all

---
#this file is to create deployment
apiVersion: apps/v1
kind: Deployment #blueprint for pods
metadata:
  name: webapp-deployment
  namespace: sheshta-app
  labels:
    app: webapp
    owner: SheshtaOps
spec:
  replicas: 3 #how many pods you want to create
  selector: #help to identify which pods are in which deployment
    matchLabels:
      app: webapp
  template: #configuration for pod
    metadata:
      labels: #key-value pair for pod- should be meaningful and relevant to users
        app: webapp
    spec:
      serviceAccountName: webapp-sa
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

      - name: tailscale
        image: tailscale/tailscale
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: ts-auth
              key: authkey
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: TS_KUBE_SECRET
          value: $(POD_NAME)
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: shesta-app
spec:
  type: ClusterIP
  selector:
    app: webapp # should match the labels of the deployment
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 3000 # port of the container of deployment

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sheshta-app
  namespace: sheshta-app
spec:
  defaultBackend:
    service:
      name: webapp-service
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - sheshta-app
